### PR TITLE
Fix README errors

### PR DESCRIPTION
**Pull request by flore77**

### CODE REVIEW

**Comment by flore77** [comment]
I will make some more updates, about `Mugshot's result`.

**Comment by flore77** [comment]
@andrei-picus-hs please review the README updates. If you have something to add/modify please do it!

**Comment by andrei-picus-hs** [comment]
@flore77 README LGTM. Please merge with master before we close this.

**Comment by flore77** [comment]
@andrei-picus-hs to close what ?

**Comment by andrei-picus-hs** [comment]
@flore77 This PR. We need to bring in the master branch into it to get the linter fixes.

**Comment by flore77** [comment]
Aa ok...yes, I understand now.

**Pull request merged**
