### PR TITLE
Bump png-crop version

### PR DESCRIPTION
**Pull request by ovidiu-bute-hs**
See issue #77

### CODE REVIEW

**Comment by ovidiu-bute-hs** [comment]
@valentin-radulescu-hs @andrei-picus-hs @flavius-tirnacop-hs please review

**Comment by valentin-radulescu-hs** [comment]
LGTM

**Comment by flavius-tirnacop-hs** [comment]
LGTM

**Comment by ovidiu-bute-hs** [comment]
I

**Pull request closed without merging**
