### PR TITLE
Upgrade to Eslint@3

### PR DESCRIPTION
**Pull request by adela-istrate-hs**

### CODE REVIEW

**Comment by adela-istrate-hs** [comment]
@valentin-radulescu-hs  @flavius-tirnacop-hs  Can you review?

**Comment by valentin-radulescu-hs** [comment]
Can you bump the mugshot version to `0.3.1` ?  This is a small linting fix that doesn't affect functionality so we only need to bump the [patch version](https://docs.npmjs.com/getting-started/semantic-versioning).

**Comment by flavius-tirnacop-hs** [comment]
LGTM

**Comment by valentin-radulescu-hs** [comment]
Also, let's go ahead and include the phantomjs package in this PR, `npm install phantomjs-prebuilt --save-dev`? [This script](https://github.com/uberVU/mugshot/blob/bd450402dcbb075ffb7e415fa796ed738baf44e9/package.json#L28) uses it so it doesn't make sense to not have it included.

LGTM otherwise

**Comment by adela-istrate-hs** [comment]
Done.

**Pull request merged**
