### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by NiGhTTraX**
## Mugshot finally has a logo!

Since GitHub is not correctly displaying the README diff you can go to [my fork](https://github.com/NiGhTTraX/mugshot/tree/logo-top) to see the logo in action. There's also a version with the logo [aligned to the right](https://github.com/NiGhTTraX/mugshot/tree/logo-right), not sure which one is better.

#### [Bigger logo, top aligned](https://github.com/NiGhTTraX/mugshot/tree/logo-top)
image

#### [Smaller logo, right aligned](https://github.com/NiGhTTraX/mugshot/tree/logo-right)
image

@flore77 @flaviusone @RadValentin @skidding @ovidiu-bute-hs @catalinmiron Please feel free to provide feedback, suggestions and/or different ideas for the logo.

### CODE REVIEW

**Comment by skidding** [comment]
Love the big one! 🍵

**Comment by flore77** [comment]
Nice job 🥇

**Comment by catalinmiron** [comment]
the big one 👍 🥇

**Comment by ovidiu-bute-hs** [comment]
Big logo all the way 😄

**Comment by ABambergher** [comment]
LGTM 😉

**Comment by RadValentin** [comment]
I's so purdy!! 😍

**Comment by RadValentin** [comment]
One question though "THE NUMBERS MASON, WHAT DO THEY MEAN...........?﻿"

**Comment by flavius-tirnacop-hs** [comment]
What a blast from the past! Big logo wins. ❤️ @NiGhTTraX

**Pull request merged**
