### PR TITLE
Fix invalid selector syntax after webdriverio update

### PR DESCRIPTION
**Pull request by adela-istrate-hs**

### CODE REVIEW

**Comment by adela-istrate-hs** [comment]
@valentin-radulescu-hs @flavius-tirnacop-hs  review?

**Comment by valentin-radulescu-hs** [comment]
LGTM

**Comment by andrei-picus-hs** [comment]
Please try to add more integration tests for the WebdriverIO adapter, especially for error handling.

**Comment by adela-istrate-hs** [comment]
ping @flavius-tirnacop-hs

**Comment by flavius-tirnacop-hs** [comment]
LGTM

**Pull request merged**
